var cart = []; var ai_t = { S: 'Hombre', P: 'Claro', O: 'Cafes' }; var userImg = null;
var db = [
    { id: 1, name: "Oversized Hoodie 'No Rules'", price: 899, cat: "hombres", img: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=400" },
    { id: 2, name: "Cargo Pants Tactical Black", price: 1150, cat: "hombres", img: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=400" },
    { id: 3, name: "Crop Hoodie 'Rebel' Red", price: 750, cat: "mujeres", img: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=400" },
    { id: 4, name: "Wide Leg Jeans Vintage Gray", price: 990, cat: "mujeres", img: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=400" }
];
function rnd(arr) { var g = document.getElementById('grid'); if (!g) return; g.innerHTML = ''; for (var i = 0; i < arr.length; i++) { var p = arr[i]; g.innerHTML += '<div class="card rounded-2xl overflow-hidden"><div class="h-56 bg-gray-950"><img src="' + p.img + '" class="w-full h-full object-cover"></div><div class="p-4 space-y-2"><h3 class="text-xs font-bold truncate text-gray-200">' + p.name + '</h3><p class="text-[#ff2a2a] font-brand font-bold text-base">$' + p.price + '</p><button onclick="add(' + p.id + ')" class="w-full bg-[#0d0d12] border border-white/5 hover:bg-[#ff2a2a] text-white font-brand text-[10px] uppercase font-bold py-2 rounded-xl transition-all">Añadir al Carrito</button></div></div>'; } }
function flt(c) { var cat = 'all'; if (c === 'hombres') { cat = 'men'; } if (c === 'mujeres') { cat = 'women'; } var ids = ['all', 'men', 'women']; for (var i = 0; i < ids.length; i++) { var b = document.getElementById('b-' + ids[i]); if (b) b.className = "px-4 py-1.5 rounded-full text-gray-400"; } var btn = document.getElementById('b-' + cat); if (btn) btn.className = "px-4 py-1.5 rounded-full bg-[#ff2a2a] text-white"; if (c === 'todos') { rnd(db); } else { rnd(db.filter(function(p) { return p.cat === c; })); } window.location.href = '#catalogo'; }
function add(id) { var p = db.find(function(x) { return x.id === id; }); var i = cart.find(function(x) { return x.id === id; }); if (i) i.q++; else cart.push({ id: p.id, name: p.name, price: p.price, img: p.img, q: 1 }); upUI(); togA(1); }
function upUI() { var c = document.getElementById('c-items'); if (!c) return; c.innerHTML = ''; var t = 0; for (var i = 0; i < cart.length; i++) { var item = cart[i]; t += item.price * item.q; c.innerHTML += '<div class="flex gap-3 bg-white/5 p-2 rounded-xl items-center text-xs"><img src="' + item.img + '" class="w-10 h-10 object-cover rounded-lg"><div class="flex-1 min-w-0"><h4 class="truncate font-bold text-[11px] text-gray-200">' + item.name + '</h4><p class="text-[#ff2a2a] font-brand text-[11px]">' + item.price + ' x' + item.q + '</p></div><button onclick="rem(' + item.id + ')" class="text-gray-500 hover:text-[#ff2a2a] px-2"><i class="fas fa-trash"></i></button></div>'; } document.getElementById('c-total').textContent = '$' + t.toFixed(2); document.getElementById('c-count').textContent = cart.reduce(function(s, k) { return s + k.q; }, 0); }
function rem(id) { cart = cart.filter(function(x) { return x.id !== id; }); upUI(); }
function togA(o) { document.getElementById('cart').classList[o ? 'add' : 'remove']('open'); }
function togM(id, o) { if (id === 'pay' && cart.length === 0) return; if (id === 'pay' && o) togA(0); document.getElementById('m-' + id).classList[o ? 'add' : 'remove']('active'); }
function togCh() { document.getElementById('c-box').classList.toggle('open'); }
function wsp(isC) { var m = isC ? "🕷️ Comprobante:\n" : "🕷️ Pedido:\n"; cart.forEach(function(i) { m += "• " + i.q + "x " + i.name + "\n"; }); window.open("https://wa.me/527122111135?text=" + encodeURIComponent(m), '_blank'); }
function selC(t, v) { ai_t[t] = v; var chips = document.querySelectorAll('[id^="ch-' + t + '-"]'); for (var i = 0; i < chips.length; i++) { chips[i].classList.remove('active'); } var target = document.getElementById('ch-' + t + '-' + v); if (target) target.classList.add('active'); snap(); }
function ldImg(e) { var f = e.target.files[0]; if (f) { var r = new FileReader(); r.onload = function(el) { userImg = el.target.result; snap(); }; r.readAsDataURL(f); } }
function snap() { var p = document.getElementById('v-photo'); var res = document.getElementById('ai-res'); var modImg = (ai_t.S === 'Hombre') ? 'https://images.unsplash.com/photo-1617137968427-85924c800a22?q=80&w=400' : 'https://images.unsplash.com/photo-1618244972963-dbee1a7edc95?q=80&w=400'; p.src = modImg; p.classList.remove('hidden'); res.innerHTML = '<strong>[SISTEMA HUD: ACTIVO]</strong><br>• Rostro Detectado y Procesado con Éxito.<br>• Armonía Biométrica detectada para tez ' + ai_t.P + ' y ojos ' + ai_t.O + '.<br><br><strong>RECOMENDACIÓN TÁCTICA:</strong><br>Para potenciar tu perfil ' + ai_t.S + ', la IA de Antony Black ha seleccionado un <strong>Saco de Gabardina Premium estructurado en juego con un Suéter de Cuello Alto Neutro</strong>. Este contraste de alta costura callejera ilumina tus facciones y te otorga un porte imponente ideal para combinar con nuestras prendas oversize.'; document.getElementById('anl').classList.remove('hidden'); }
function bot(e) { e.preventDefault(); var i = document.getElementById('c-in'); var m = document.getElementById('c-msg'); var t = i.value.trim().toLowerCase(); if (!t) return; m.innerHTML += '<div class="text-right text-[#ff2a2a] font-brand font-bold">' + i.value + '</div>'; i.value = ''; setTimeout(function() { var r = "Contacto directo: WhatsApp 7122111135. 🕷️"; if (t.indexOf('precio') !== -1 || t.indexOf('cuanto') !== -1) { r = "Sudadera: $899, Pants: $1150, Crop: $750. Puedes ver el total didáctico sumado en tu bolsa."; } else if (t.indexOf('talla') !== -1 || t.indexOf('medida') !== -1) { r = "Corte <strong>Oversize Premium</strong>. Didáctica: Si buscas el estilo holgado de la marca, pide tu talla de siempre. Si la quieres justa, pide una menos."; } else if (t.indexOf('material') !== -1 || t.indexOf('tela') !== -1) { r = "Algodón pesado premium (Heavy Cotton) de alto gramaje. No se deforma y mantiene la caída urbana perfecta."; } else if (t.indexOf('envio') !== -1 || t.indexOf('entrega') !== -1) { r = "Entregamos gratis en Desviación Jocotitlán, San Pedro de los Baños y Jocotitlán Centro (Frente a Palacio)."; } else if (t.indexOf('pago') !== -1 || t.indexOf('cuenta') !== -1) { r = "CLABE SPEI: 722969010522000447 (Mercado Pago Wallet) o directo con tarjeta usando el botón azul de tu bolsa."; } m.innerHTML += '<div class="bg-[#121216] p-2.5 rounded-lg mt-1 border border-white/5">' + r + '</div>'; m.scrollTop = m.scrollHeight; }, 400); }
rnd(db); snap();
